
FROM    alpine:3.15.1 AS build

WORKDIR /app

RUN     apk add --no-cache protoc

COPY    ./frontend/src/proto/robot.proto .

# build proto descriptor
RUN     protoc --include_imports --include_source_info \
    --descriptor_set_out=robot.pb robot.proto

FROM    envoyproxy/envoy:v1.22.0

COPY    --from=build /app/robot.pb /tmp/
